### ISSUE TITLE
noch zu prüfende Kodierungen (generell)

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#117]
- [x] KSEEVerweis
  - auf I bleibt Text (ggf. später Link nachtragen)
  - auf II Link zunächst auf Datei
- [x] Zwischenüberschriften zum Gliedern
- [x] Buchtitel: Umbruch wie Vorlage (dariok/w2tei#12, #95)
- [x] Buchtitel: Einrückung nach Vorlage (dariok/w2tei#12)
- [x] subscriptio etc.: Einrückung (dariok/w2tei#12)
- [x] Expansionen (vgl. auch #107)

**Comment by dariok** [comment]
Buchtitel vorläufig umgesetzt mit https://github.com/dariok/w2tei/commit/b1466508127b07163007241cab4ca7e3e609b469

**Comment by dariok** [comment]
Zwischenüberschriften umgesetzt in https://github.com/dariok/w2tei/commit/b1f954f21719259c59381886acfa1e523b738ce0

**Comment by dariok** [comment]
erledigt mit https://github.com/dariok/w2tei/commit/7f8eea08e36f82f888296118cdbde589f9d85ba9
